---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-addons
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/addons
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/configs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rook-ceph
  dependsOn:
    - name: infra-addons
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
 # name: ceph-cluster
  #namespace: flux-system
#spec:
 # interval: 10m
  #path: ./infrastructure/rook-ceph/cephcluster
  #prune: true
  #sourceRef:
   # kind: GitRepository
    #name: flux-system
  #dependsOn:
   # - name: rook-ceph
  #targetNamespace: rook-ceph
  #wait: true
  #timeout: 5m
  #retryInterval: 1m
